[versions]
kotlin = "2.1.10"
jdk = "22"
kotlinxDatetime = "0.6.2"
kotlinxSerializationJSON = "1.8.0"
kotlinxCoroutines = "1.10.1"
kotlinxAtomicfu = "0.27.0"
kotlinxKover = "0.9.1"
nettyVersion = "4.2.0.RC2"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxAtomicfu =  { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu" }

netty = { module = "io.netty:netty-all", version.ref = "nettyVersion" }

[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines", "kotlinxAtomicfu"]

[plugins]
kotlinxKover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinxKover" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
