[package]
name = "kotty-miow"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "kottymiow"

[build-dependencies]
cbindgen = "0.28"

[dependencies]
mio = { version = "1", features = ["os-poll", "net"] }
